version: '3.7'
services:
  api:
    build:
      context: ./api
      dockerfile: ../docker/Dockerfile.api # contextで指定した位置からDockerfileへのパス
      
    command: go run main.go
    container_name: book-review-api
    ports:
      - "1323:1323"
    volumes:
      - ./api:/app
  front:
    build:
      context: ./front
      dockerfile: ../docker/Dockerfile.front # contextで指定した位置からDockerfileへのパス
      
    # command: go run main.go
    container_name: book-review-front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    tty: true